### PR TITLE
project review for apple project

### PR DESCRIPTION
**Pull request by saintaze**

### CODE REVIEW

**Review by bellom — CHANGES_REQUESTED** [review]
Hi @saintaze, 
**Note: For every reviewer reviewing your code follows the the Microverse review guidelines**
Good job. Here is the checklist for your project.
- To consider the project 'complete' it must satisfy the following points:
## General
- [x] The project has a descriptive README.md
## Navigation bar
* [x] It should use a linear gradient as background color
* [ ] It should be made of nine different buttons with the Apple logo on the leftmost section and a search field on the rightmost section
* [ ] It should be within the <main> tag
## Search field
-  [ ] The search field should be an `<input>` HTML tag with the *focus* effect enabled
## Background
-  [x] The main content should be wrapped around `<main>` tags and have an image set as background
## Main Content Links
* [x] There should be three links
* [x] Each link is an `<div>` HTML tag, with a `<a>` tag inside it.
* [x] The `<a>` tag inside the `<div>` tag should use an image as background -- \[ \] The text on the original page is actually an image
## Bottom
-  [x] It has buttons positioned either as *floats* or *display flex*
## Footer 
* [x] It should be wrapped by `<footer>` tags
* [x] The top part is made of four `<a>` tags with `` tags inside it
* [x] The `<a>` tags should use an image as a background
* [x] The bottom part should include links like copyright, terms of use, and privacy policy

**Note: Always Compare your web page to the original website, it will really help, your web page looks a little bit off, see for yourself** :point_down:

image

**After fixing the _**unchecked**_ issues please send another request to re-review this project.**

For more question or help reach me on slack with handle - @sean bellom

**Comment by saintaze** [comment]
Hey,

Want to highlight some points,

1) Navbar should not be in the main tag. The main tag is used for the main content of the website and navbar is not the content

2) Under the background section, you again said to wrap everything in main tag. But this page doesn't have any content, so it is not required. The topmost part is a header and not main.

**Comment by Torres-ssf** [comment]
Hi there @saintaze...
I totally understand you. Many time I had a different opinion about what the TSE said about my code. But we TSE have to follow Microverse guidelines when correcting projects. These guidelines were created by Microverse engineers. In fact, we TSE are not allowed to approve any project that does not match these guidelines. In the last review, my friend @bellom show those guidelines to you in order to make easier for you to get this project approved. Microverse is improving every single day, we try to give the best learning experience to the students. So I want to ask you when filling the form for this project, please put your feedback about the things that you do not agree in this project. Microverse take students feedback very seriously, and they may review the guidelines of this project to see if they are the most adequate.

There are still some things that we need to change in your project:

- [ ] For the sake of this project, the navbar must be inside the `main` tag.

- [ ] The main part of this project includes the navbar and the 3 main sentences.

- [ ] Each one of these 3 main sentences must be a `div` inside an anchor tag (`a`). The texts are in reality images, so you need to use the `div` background to load them.

- [ ] The `footer` of this page is divided into two parts. Top and bottom. So the footer starts where you used the `aside` tag. The top part of the `footer` contains the 4 promo images.

- [ ] For the 4 promo images you have to use the same approach of the 3 main sentences. Each one of those 4 images must be a `div` inside an anchor (`a`) tag. Using the background of the div to load the images.

- [ ] Kindly put a link with a live version of your page in the readme file.

Please kindly make these changes and submit to code review again.

**Comment by saintaze** [comment]
Hey Sergio, 

I made most of the changes, please kindly accept it. As you know Ariel talked about new review guidelines. Currently, the suggestions you made are opinionated and one thing can be done in 100 of ways in programming. So kindly accept the project, so I can move on.

**Comment by Torres-ssf** [comment]
### Great Job @saintaze 👍
You can merge to master now.

**Pull request merged**
